In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
orders = pd.read_csv('/kaggle/input/datasets/shrikantlala/ecommerce-date-time/orders.csv')
orders.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [3]:
# sns.load_dataset('flights')
msg = pd.read_csv('/kaggle/input/datasets/shrikantlala/ecommerce-date-time/messages.csv')
msg.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [4]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

# Covert to datetime

In [5]:
orders['date'] = pd.to_datetime(orders['date'])
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

# extracting from datetime
1. year
2. month
3. day
4. month_name() 
5. dayofweek (day of the week)

In [6]:
orders['year'] = orders['date'].dt.year
orders.head()

        date  product_id  city_id  orders  year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018
2 2018-10-23        1859       25       1  2018
3 2019-08-17        7292       25       1  2019
4 2019-01-06        4344       25       3  2019

In [7]:
orders['month'] = orders['date'].dt.month
orders.head()

        date  product_id  city_id  orders  year  month
0 2019-12-10        5628       25       3  2019     12
1 2018-08-15        3646       14     157  2018      8
2 2018-10-23        1859       25       1  2018     10
3 2019-08-17        7292       25       1  2019      8
4 2019-01-06        4344       25       3  2019      1

In [8]:
orders['day'] = orders.date.dt.day
orders.head()

        date  product_id  city_id  orders  year  month  day
0 2019-12-10        5628       25       3  2019     12   10
1 2018-08-15        3646       14     157  2018      8   15
2 2018-10-23        1859       25       1  2018     10   23
3 2019-08-17        7292       25       1  2019      8   17
4 2019-01-06        4344       25       3  2019      1    6

In [9]:
# orders.drop(columns=['actual_date'],inplace=True)
orders.head()

        date  product_id  city_id  orders  year  month  day
0 2019-12-10        5628       25       3  2019     12   10
1 2018-08-15        3646       14     157  2018      8   15
2 2018-10-23        1859       25       1  2018     10   23
3 2019-08-17        7292       25       1  2019      8   17
4 2019-01-06        4344       25       3  2019      1    6

In [10]:
orders['month_name'] = orders.date.dt.month_name()
orders.head()

        date  product_id  city_id  orders  year  month  day month_name
0 2019-12-10        5628       25       3  2019     12   10   December
1 2018-08-15        3646       14     157  2018      8   15     August
2 2018-10-23        1859       25       1  2018     10   23    October
3 2019-08-17        7292       25       1  2019      8   17     August
4 2019-01-06        4344       25       3  2019      1    6    January

In [11]:
orders['day_of_week'] = orders.date.dt.dayofweek
orders.head()

,date,product_id,city_id,orders,year,month,day,month_name,day_of_week
0,2019-12-10,5628,25,3,2019,12,10,December,1
1,2018-08-15,3646,14,157,2018,8,15,August,2
2,2018-10-23,1859,25,1,2018,10,23,October,1
3,2019-08-17,7292,25,1,2019,8,17,August,5
4,2019-01-06,4344,25,3,2019,1,6,January,6